implemented tests and algorithm
mayahp/step-portfolio pull request #15
Opened 2020-06-19 18:35 UTC by mayahp

Created the meeting algorithm, made the given tests pass + wrote some more.

2020-06-19 19:11 UTC, danhoshow requested changes

2020-06-19 19:11 UTC, danhoshow commented on walkthroughs/week-5-tdd/project/src/test/java/com/google/sps/FindMeetingQueryTest.java
> +    private static final Collection < Event > NO_EVENTS = Collections.emptySet();
remove the unnecessary spaces... `private static final Collection<Event> NO_EVENTS = Collections.emptySet()`

2020-06-19 19:11 UTC, danhoshow commented on walkthroughs/week-5-tdd/project/src/test/java/com/google/sps/FindMeetingQueryTest.java
> +    private static final Collection < Event > NO_EVENTS = Collections.emptySet();
throughout the rest of this PR, too

2020-06-19 19:11 UTC, danhoshow commented on walkthroughs/week-5-tdd/project/src/test/java/com/google/sps/FindMeetingQueryTest.java
> +    public void optionsForNoAttendees() {
In general (at Google), the names should "include the condition being tested and the expected outcome." I'm not sure if the test function names were given to you, but a name like `queryForNoAttendeesReturnsWholeDay` would be better

2020-06-19 19:11 UTC, danhoshow commented on walkthroughs/week-5-tdd/project/src/test/java/com/google/sps/FindMeetingQueryTest.java
> +    public void optionsForNoAttendees() {
if you could apply that throughout this file too

2020-06-22 15:20 UTC, mayahp commented on walkthroughs/week-5-tdd/project/src/test/java/com/google/sps/FindMeetingQueryTest.java
> +    public void optionsForNoAttendees() {
They gave us these test names, but I can edit the ones that I made up myself

2020-06-22 16:38 UTC, danhoshow approved these changes

2020-06-22 20:47 UTC, merged